@buyerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjIsImlhdCI6MTc0MzYyMzk0NiwiZXhwIjoxNzQzNzEwMzQ2fQ.NG9RdcIYnj0i2Tql8Xc9WMQoXRtL7MpOhI4bGtcfjpI
###
POST {{URL}}/auth/login

###
POST {{URL}}/auth/register/buyer
Content-Type: application/json

{
	"name":"Moeez Ali Test 3",
	"email":"moeezali2375@gmail.com",
	"password":"1234"
}

###
GET {{URL}}/auth/buyer/verify-token/106304
Authorization: Bearer {{buyerToken}}

###
GET {{URL}}/auth/buyer/regenerate-token
Authorization: Bearer {{buyerToken}}


###
POST {{URL}}/auth/login
Content-Type:application/json

{
	"email":"moeezali2375@gmail.com",
	"password":"12345"
}

###
PUT {{URL}}/auth/reset-password
Content-Type: application/json

{
	"email":"moeezali2375@gmail.com"
}

###
POST {{URL}}/auth/reset-password
Content-Type: application/json

{
	"email":"moeezali2375@gmail.com",
	"verificationToken":"0133ec4f09b7638f881de036d38786222299483f5b2baba9e947da1bdbb111649bbee0c157894db5899e63b436ba293403edf69a65eb65f4b1c6c1e34929e9e5",
	"newPassword":"1234"
}
